/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_esoft;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author PRIMESH
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
         fillTable();
         cusid();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnadd1 = new javax.swing.JButton();
        btnupdate1 = new javax.swing.JButton();
        btndelete1 = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbCutomer = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        txtcustomerName = new javax.swing.JTextField();
        txtcontactNO = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        txtAddress = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jmpro = new javax.swing.JMenuItem();
        jmin = new javax.swing.JMenuItem();
        jmsup = new javax.swing.JMenuItem();
        jmexit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Customer Id");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 130, 30));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Address");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 130, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 130, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Contact No");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 130, 30));

        btnadd1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnadd1.setForeground(new java.awt.Color(204, 0, 0));
        btnadd1.setText("Add");
        btnadd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 120, 40));

        btnupdate1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnupdate1.setForeground(new java.awt.Color(204, 0, 0));
        btnupdate1.setText("Update");
        btnupdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdate1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 120, 40));

        btndelete1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndelete1.setForeground(new java.awt.Color(204, 0, 0));
        btndelete1.setText("Delete");
        btndelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelete1ActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 120, 40));

        btnclear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnclear.setForeground(new java.awt.Color(204, 0, 0));
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 120, 40));

        jtbCutomer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtbCutomer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtbCutomer.setForeground(new java.awt.Color(0, 0, 153));
        jtbCutomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbCutomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbCutomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbCutomer);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 900, 160));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Customer Name");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 150, 30));

        txtcustomerName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtcustomerName.setForeground(new java.awt.Color(0, 0, 153));
        txtcustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustomerNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtcustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 250, 30));

        txtcontactNO.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtcontactNO.setForeground(new java.awt.Color(0, 0, 153));
        txtcontactNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontactNOActionPerformed(evt);
            }
        });
        getContentPane().add(txtcontactNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 210, 30));

        txtemail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtemail.setForeground(new java.awt.Color(0, 0, 153));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 250, 30));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Customer Details");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 400, 40));

        lblID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 130, 30));

        txtAddress.setForeground(new java.awt.Color(0, 0, 204));

        txtaddress.setColumns(20);
        txtaddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtaddress.setForeground(new java.awt.Color(0, 0, 153));
        txtaddress.setRows(5);
        txtAddress.setViewportView(txtaddress);

        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_esoft/wallpaper2you_179078.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1620, 860));

        jMenu3.setText("File");

        jmpro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jmpro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jmpro.setForeground(new java.awt.Color(0, 51, 51));
        jmpro.setText("Stock");
        jmpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmproActionPerformed(evt);
            }
        });
        jMenu3.add(jmpro);

        jmin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jmin.setForeground(new java.awt.Color(0, 51, 51));
        jmin.setText("Invoice");
        jmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jminActionPerformed(evt);
            }
        });
        jMenu3.add(jmin);

        jmsup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jmsup.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jmsup.setForeground(new java.awt.Color(0, 51, 51));
        jmsup.setText("Add supplier");
        jmsup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmsupActionPerformed(evt);
            }
        });
        jMenu3.add(jmsup);

        jmexit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jmexit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jmexit.setForeground(new java.awt.Color(0, 51, 51));
        jmexit.setText("Exit");
        jmexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmexitActionPerformed(evt);
            }
        });
        jMenu3.add(jmexit);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnadd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd1ActionPerformed

        String j=lblID.getText();
        int jj=Integer.parseInt(j);
        String d=txtcustomerName.getText();
        String f=txtcontactNO.getText();
        int cn=Integer.parseInt(f);
        String h=txtemail.getText();
        String i=txtaddress.getText();

        try {

            Connection con = DBConnection.getConnection();
            String sqlQurey = "insert into customer_details (customerId,customerName,contactNO,email,address) values (?,?,?,?,?)";
            PreparedStatement ps= con.prepareStatement(sqlQurey);

            ps.setInt(1, jj);
            ps.setString(2, d);
            ps.setInt(3, cn);
            ps.setString(4,h);
            ps.setString(5,i);
            ps.execute();

            JOptionPane.showMessageDialog(null, "Record Insert Successfully", "invoice", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Record Insert Successfully ");
            fillTable();
            clear();
            cusid();

        }catch (SQLException ex) {

            System.out.println("error");
            ex.printStackTrace();
        }
        // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_btnadd1ActionPerformed

    private void btnupdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdate1ActionPerformed
        String j= lblID.getText();
        int jj=Integer.parseInt(j);
        String d=txtcustomerName.getText();
        String f=txtcontactNO.getText();
        int cn=Integer.parseInt(f);
        String h=txtemail.getText();
        String i=txtaddress.getText();

        try {

            // TODO code application logic here
            Connection con = DBConnection.getConnection();

            String sqlQurey = "update customer_details Set customerName=?,contactNo=?,email=?,address=? where customerId="+jj;
            PreparedStatement ps= con.prepareStatement(sqlQurey);
            ps.setString(1,d);
            ps.setInt(2,cn);
            ps.setString(3,h);
            ps.setString(4,i);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Record Update Successfully", "customer_details", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Record Insert Successfully ");
            fillTable();
            clear();
            cusid();

        }catch (SQLException ex) {

            System.out.println("error");
            ex.printStackTrace();
        }
        // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_btnupdate1ActionPerformed

    private void btndelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelete1ActionPerformed
        String a= lblID.getText();
        int id= Integer.parseInt(a);

        try {
            // TODO code application logic here
            Connection con = DBConnection.getConnection();
            Statement st = con.createStatement();

            String sqlQurey = "delete from customer_details where customerId="+id;
            PreparedStatement ps= con.prepareStatement(sqlQurey);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Record Delete Successfully", "customer", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Record Delete Successfully ");
            fillTable();
            clear();

            System.out.println("Record Delete Successfully ");
        }catch (SQLException ex) {
            System.out.println("error");
            ex.printStackTrace();
        }
        // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_btndelete1ActionPerformed
public  void fillTable()
    {
        try {
            DefaultTableModel model = new DefaultTableModel(new String[]{"customerId", "customerName", "ContactNo", "email","address"}, 0);
            
            Connection con = DBConnection.getConnection();
            String sql="SELECT * FROM customer_details";
            
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            TableModel tb = model;
            tb =  DbUtils.resultSetToTableModel(rs);
           jtbCutomer.setModel(tb);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
          
    }
    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        clear();
    }//GEN-LAST:event_btnclearActionPerformed

    private void jtbCutomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbCutomerMouseClicked
        DefaultTableModel mode1=(DefaultTableModel)jtbCutomer.getModel();
        int select = jtbCutomer.getSelectedRow();
        lblID.setText(mode1.getValueAt(select,0).toString());
        txtcustomerName.setText(mode1.getValueAt(select,1).toString());
        txtcontactNO.setText(mode1.getValueAt(select,2).toString());
        txtemail.setText(mode1.getValueAt(select,3).toString());
        txtaddress.setText(mode1.getValueAt(select,4).toString());

        // TODO add your handling code here:
    }//GEN-LAST:event_jtbCutomerMouseClicked
void clear()
{
        
        txtcustomerName.setText("");
        txtcontactNO.setText("");
        txtemail.setText("");
        txtaddress.setText("");
         cusid();

}
void cusid() 
{
 try {
            // TODO code application logic here
            Connection con = DBConnection.getConnection();
             Statement st = con.createStatement();
        
           ResultSet rs= st.executeQuery("SELECT MAX(customerId) FROM customer_details ");
            while (rs.next()) 
            {
        int max=rs.getInt(1);
        int totmx =max+1;
        String m=Integer.toString(totmx);
         lblID.setText(m);
            }
              
            System.out.println("Record inivoiceNo get Successfully ");
                       
        }catch (SQLException ex) {
            System.out.println("error");
            ex.printStackTrace();
        }
}
    private void txtcustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustomerNameActionPerformed

    private void txtcontactNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontactNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontactNOActionPerformed

    private void jmproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmproActionPerformed
        new Stock().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jmproActionPerformed

    private void jminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jminActionPerformed
         this.setVisible(false);
        new Invoice().setVisible(true);// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jminActionPerformed

    private void jmsupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmsupActionPerformed
        this.setVisible(false);
        new Supplier_details().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jmsupActionPerformed

    private void jmexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmexitActionPerformed
       this.setVisible(false);  
        // TODO add your handling code here:
    }//GEN-LAST:event_jmexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            Customer myFrame = new Customer();
            myFrame.setVisible(true);
            myFrame.setExtendedState(myFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btnadd1;
    private static javax.swing.JButton btnclear;
    private static javax.swing.JButton btndelete1;
    private static javax.swing.JButton btnupdate1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jmexit;
    private javax.swing.JMenuItem jmin;
    private javax.swing.JMenuItem jmpro;
    private javax.swing.JMenuItem jmsup;
    private static javax.swing.JTable jtbCutomer;
    private javax.swing.JLabel lblID;
    private javax.swing.JScrollPane txtAddress;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JTextField txtcontactNO;
    private javax.swing.JTextField txtcustomerName;
    private javax.swing.JTextField txtemail;
    // End of variables declaration//GEN-END:variables
}
