/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_esoft;

import java.awt.Toolkit;
import java.sql.Connection;
import java.util.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author PRIMESH
 */
public class Invoice extends javax.swing.JFrame {

    /**
     * Creates new form Invoice
     */
    public Invoice() {
        initComponents();
        fillTable();
        proTable();
        cusTable();
        maxin();
        date();
//        Toolkit tk= Toolkit .getDefaultToolkit();
//          int xsize =(int) tk.getScreenSize().getWidth();
//          int ysize =(int) tk.getScreenSize().getHeight();
//         this.setSize(xsize,ysize);

    }

    void  date()
    {
           Date   d= new Date();
           String s= "hh:mm:ss a";
           SimpleDateFormat sd= new SimpleDateFormat(s);
           
            
            lblINdate.setText(LocalDate.now().toString());  
            lblNtime.setText(sd.format(d));  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField11 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnINprint = new javax.swing.JButton();
        lblNtime = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtINquntity = new javax.swing.JTextField();
        lblINdate = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnINAdd_pro = new javax.swing.JButton();
        btnINclear_pro = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblINcusname = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_pro = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblproducts = new javax.swing.JTable();
        lblINproductId = new javax.swing.JLabel();
        lblINproductname = new javax.swing.JLabel();
        lblINprice = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCuId = new javax.swing.JTable();
        lblINcusId = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblSubtot = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblINtotal = new javax.swing.JLabel();
        lblINitemratio = new javax.swing.JLabel();
        btnINremove1 = new javax.swing.JButton();
        lblINinvoiceNo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel16 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmpro = new javax.swing.JMenuItem();
        jmcus = new javax.swing.JMenuItem();
        jmsup = new javax.swing.JMenuItem();
        jmexit = new javax.swing.JMenuItem();

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Customer Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 130, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Invoice Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Time");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 80, 20));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INVOICE");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 17, 300, 40));

        btnINprint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnINprint.setForeground(new java.awt.Color(204, 0, 0));
        btnINprint.setText("Print");
        btnINprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnINprintActionPerformed(evt);
            }
        });
        getContentPane().add(btnINprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 590, 140, 40));

        lblNtime.setBackground(new java.awt.Color(255, 255, 255));
        lblNtime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNtime.setForeground(new java.awt.Color(0, 0, 153));
        lblNtime.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblNtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 190, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Product Id");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 130, 23));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Price");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 130, 23));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Quantity");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 130, 23));

        txtINquntity.setBackground(new java.awt.Color(153, 255, 255));
        txtINquntity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtINquntity.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtINquntity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtINquntityActionPerformed(evt);
            }
        });
        txtINquntity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtINquntityKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtINquntityKeyReleased(evt);
            }
        });
        getContentPane().add(txtINquntity, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 170, 30));

        lblINdate.setBackground(new java.awt.Color(255, 255, 255));
        lblINdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblINdate.setForeground(new java.awt.Color(0, 0, 153));
        lblINdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblINdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 140, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Product Name");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 130, 23));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Item Ratio");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 100, 20));

        btnINAdd_pro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnINAdd_pro.setForeground(new java.awt.Color(204, 0, 0));
        btnINAdd_pro.setText("Add");
        btnINAdd_pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnINAdd_proActionPerformed(evt);
            }
        });
        getContentPane().add(btnINAdd_pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 120, 40));

        btnINclear_pro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnINclear_pro.setForeground(new java.awt.Color(204, 0, 0));
        btnINclear_pro.setText("Clear");
        btnINclear_pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnINclear_proActionPerformed(evt);
            }
        });
        getContentPane().add(btnINclear_pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 120, 40));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 160, 110, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Customer ID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 90, 120, -1));

        lblINcusname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblINcusname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblINcusname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 120, 130, 30));

        tbl_pro.setBackground(new java.awt.Color(159, 242, 209));
        tbl_pro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbl_pro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbl_pro.setForeground(new java.awt.Color(0, 0, 153));
        tbl_pro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane2.setViewportView(tbl_pro);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 790, 140));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Total");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 90, 20));

        tblproducts.setBackground(new java.awt.Color(102, 231, 219));
        tblproducts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblproducts.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblproducts.setForeground(new java.awt.Color(0, 0, 153));
        tblproducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblproducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblproductsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblproducts);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 160));

        lblINproductId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblINproductId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblINproductId, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 170, 30));

        lblINproductname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblINproductname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblINproductname, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 170, 30));

        lblINprice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblINprice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblINprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 170, 30));

        tblCuId.setBackground(new java.awt.Color(139, 239, 200));
        tblCuId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblCuId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblCuId.setForeground(new java.awt.Color(0, 0, 153));
        tblCuId.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCuId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCuIdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCuId);
        if (tblCuId.getColumnModel().getColumnCount() > 0) {
            tblCuId.getColumnModel().getColumn(0).setMinWidth(75);
            tblCuId.getColumnModel().getColumn(1).setMinWidth(100);
            tblCuId.getColumnModel().getColumn(3).setMinWidth(200);
            tblCuId.getColumnModel().getColumn(3).setMaxWidth(200);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 270, 490, 140));

        lblINcusId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblINcusId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblINcusId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 80, 130, 30));

        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 530, -1, 0));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("SubTotal");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 510, 90, 20));

        lblSubtot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSubtot.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblSubtot, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 510, 120, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Invoice No");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 20));

        lblINtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblINtotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblINtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 170, 30));

        lblINitemratio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblINitemratio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblINitemratio, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 170, 30));

        btnINremove1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnINremove1.setForeground(new java.awt.Color(204, 0, 0));
        btnINremove1.setText("Remove Row");
        btnINremove1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnINremove1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnINremove1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, -1, 40));

        lblINinvoiceNo.setBackground(new java.awt.Color(255, 255, 255));
        lblINinvoiceNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblINinvoiceNo.setForeground(new java.awt.Color(0, 0, 153));
        lblINinvoiceNo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblINinvoiceNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 110, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("CustomerTable");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 250, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Products Table");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Item Table");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, -1, -1));

        jToolBar1.setRollover(true);
        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_esoft/130743-blue-green-background-2149x1440-for-ipad-2.jpg"))); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1620, 780));

        jMenuBar1.setPreferredSize(new java.awt.Dimension(36, 26));

        jMenu1.setText("File");

        jmpro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jmpro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jmpro.setForeground(new java.awt.Color(0, 51, 51));
        jmpro.setText("Stock");
        jmpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmproActionPerformed(evt);
            }
        });
        jMenu1.add(jmpro);

        jmcus.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jmcus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jmcus.setForeground(new java.awt.Color(0, 51, 51));
        jmcus.setText("Add customer");
        jmcus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmcusActionPerformed(evt);
            }
        });
        jMenu1.add(jmcus);

        jmsup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jmsup.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jmsup.setForeground(new java.awt.Color(0, 51, 51));
        jmsup.setText("Add supplier");
        jmsup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmsupActionPerformed(evt);
            }
        });
        jMenu1.add(jmsup);

        jmexit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jmexit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jmexit.setForeground(new java.awt.Color(0, 51, 51));
        jmexit.setText("Exit");
        jmexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmexitActionPerformed(evt);
            }
        });
        jMenu1.add(jmexit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void btnINprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnINprintActionPerformed
insertIN (); 
clear1();
maxin();
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnINprintActionPerformed
int maxin()
{ 
    int totmx = 0;
    try {
            // TODO code application logic here
            Connection con = DBConnection.getConnection();
             Statement st = con.createStatement();
        
           ResultSet rs= st.executeQuery("SELECT MAX(InvoiceNO) FROM invoice_details ");
            while (rs.next()) 
            {
        int max=rs.getInt(1);
         totmx =max+1;
        
        String m=Integer.toString(totmx);
         lblINinvoiceNo.setText(m);
            }
              
            System.out.println("Record inivoiceNo get Successfully ");
                       
        }catch (SQLException ex) {
            System.out.println("error");
            ex.printStackTrace();
        }
    return totmx;
}

void clear(){
  lblINtotal.setText("");
  lblINproductId.setText("");
  lblINprice.setText(""); 
  txtINquntity.setText("");
  lblINitemratio.setText("");
  lblINproductname.setText("");
   }
 void clear1(){
  lblINtotal.setText("");
  lblINproductId.setText("");
  lblINprice.setText(""); 
  txtINquntity.setText("");
  lblINitemratio.setText("");
  lblINproductname.setText("");
  lblINcusId.setText("");
  lblINcusname.setText("");
  lblSubtot.setText("");
  }

    private void txtINquntityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtINquntityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtINquntityActionPerformed
   public  void fillTable()
    {
        //int iv=Integer.parseInt(lblINinvoiceNo.getText());
        try {
            DefaultTableModel model = new DefaultTableModel(new String[]{}, 0);
            
            Connection con = DBConnection.getConnection();
            String sql="SELECT * FROM customer_brought_products where invoiceNo="+maxin();
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            TableModel tb = model;
            tb =  DbUtils.resultSetToTableModel(rs);
          tbl_pro.setModel(tb);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
          
    }
    public  void proTable()
    {
        try {
            DefaultTableModel model = new DefaultTableModel(new String[]{}, 0);
            
            Connection con = DBConnection.getConnection();
            String sql="SELECT * FROM products";
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            TableModel tb = model;
            tb =  DbUtils.resultSetToTableModel(rs);
        tblproducts.setModel(tb);
             
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
       }
    public  void cusTable()
    {
        try {
            DefaultTableModel model = new DefaultTableModel(new String[]{}, 0);
            
            Connection con = DBConnection.getConnection();
            String sql="SELECT * FROM customer_details";
                        
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            TableModel tb = model;
            tb =  DbUtils.resultSetToTableModel(rs);
       tblCuId.setModel(tb);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
       }
   
    private void btnINAdd_proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnINAdd_proActionPerformed

        String a=lblINproductId.getText();
        String b=lblINinvoiceNo.getText();
           int io=Integer.parseInt(b);
        String c=lblINcusId.getText(); 
        if (c=="")
         {
            JOptionPane.showMessageDialog(null, "Pleace Insert Customer Details ", "INVOICE", JOptionPane.INFORMATION_MESSAGE);
            
         }
        String d=lblINproductname.getText();
       String e=lblINprice.getText();
       double p=Double.parseDouble(e);
        String f=txtINquntity.getText();
           int qn=Integer.parseInt(f);
        String h=lblINtotal.getText();
         double t=Double.parseDouble(h);
                
try {
     
            Connection con = DBConnection.getConnection();
             String sql="insert into customer_brought_products() values(?,?,?,?,?,?,?)";
             PreparedStatement s= con.prepareStatement(sql);     
            
             s.setString(1,a);
             s.setInt(2,io);
             s.setString(3,c);
             s.setString(4,d);
             s.setDouble(5,p);
             s.setInt(6,qn);
             s.setDouble(7,t);
             s.execute();
                       
           // JOptionPane.showMessageDialog(null, "Record Insert Successfully", "invoice", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Record Insert Successfully ");
            fillTable();
            update();
            subup();
            

            clear();
        }catch (SQLException ex) {
            
            System.out.println("error");
            ex.printStackTrace();
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnINAdd_proActionPerformed
void insertIN ()
{
String a=lblINinvoiceNo.getText();
int   io=Integer.parseInt(a);
String b=lblINcusId.getText();
String c=lblINcusname.getText();
String id=lblINdate.getText();
String it=lblNtime.getText();
String sb=lblSubtot.getText(); 
 double t=Double.parseDouble(sb);
    try
    {
     Connection con = DBConnection.getConnection();
     String mysql="insert into invoice_details (invoiceNo,CustomerId,CustomerName,invoiceDate,time,subTotal) values(?,?,?,?,?,?)";
             PreparedStatement x= con.prepareStatement(mysql);
             x.setInt(1,io);
             x.setString(2,b);
             x.setString(3,c);
             x.setString(4,id);
             x.setString(5,it);
             x.setDouble(6,t); 
             x.execute();
            JOptionPane.showMessageDialog(null, "Invoice Print Successfully", "invoice", JOptionPane.INFORMATION_MESSAGE);
           } 
    catch (SQLException ex) 
    {
       System.out.println("error");
       ex.printStackTrace(); 
    }
}
    void update()
    {
       String a= lblINproductId.getText();
       String b= lblINitemratio.getText();
       String c=txtINquntity.getText();
         int qn=Integer.parseInt(c);
       try {
            // TODO code application logic here
            Connection con = DBConnection.getConnection();
              String sqlQurey = "update products Set itemratio= itemratio -" + qn+ " where productId="+a;
            PreparedStatement ps= con.prepareStatement(sqlQurey);
             ps.execute();
            //JOptionPane.showMessageDialog(null, "Record update Successfully", "stock", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Record update Successfully ");
           proTable();
                    }catch (SQLException ex) {
                        System.out.println("error");
            ex.printStackTrace();
        }
        // TODO add your handling code here:
                
    }
  
        void subup()
    {
     
       String a= lblINinvoiceNo.getText();
         int in=Integer.parseInt(a);
       
       
 try {
            // TODO code application logic here
            Connection con = DBConnection.getConnection();
             Statement st = con.createStatement();
        
           ResultSet rs= st.executeQuery("SELECT SUM(Total) FROM customer_brought_products where invoiceNo="+ in);
            while (rs.next()) 
            {
        double sum=rs.getDouble(1);
        String m=Double.toString(sum);
         lblSubtot.setText(m);
         
            }
                                  
            //JOptionPane.showMessageDialog(null, "Record update Successfully", "subtotal", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Record update Successfully ");
           
            
        }catch (SQLException ex) {
            
            System.out.println("error");
            ex.printStackTrace();
        }
    }
    
//    void space()
//    {
//         if(lblINcusId.getText().trim().isEmpty() && lblINcusname.getText().trim().isEmpty()) 
//         { //or your condition which validates i
//          JOptionPane.showMessageDialog(null, "please", "subtotal", JOptionPane.INFORMATION_MESSAGE);
//         }  
//    }
    
    private void btnINclear_proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnINclear_proActionPerformed
 clear1();        // TODO add your handling code here:
    }//GEN-LAST:event_btnINclear_proActionPerformed

    private void tblproductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblproductsMouseClicked
DefaultTableModel mode1=(DefaultTableModel)tblproducts.getModel();
int select = tblproducts.getSelectedRow();
lblINproductId.setText(mode1.getValueAt(select,0).toString());
lblINproductname.setText(mode1.getValueAt(select,2).toString());
lblINprice.setText(mode1.getValueAt(select,3).toString());
lblINitemratio.setText(mode1.getValueAt(select,4).toString());

        // TODO add your handling code here:
    }//GEN-LAST:event_tblproductsMouseClicked

    private void txtINquntityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtINquntityKeyPressed
       // TODO add your handling code here:
    }//GEN-LAST:event_txtINquntityKeyPressed

    private void txtINquntityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtINquntityKeyReleased
     
        int f=0; 
    String s=txtINquntity.getText();
    String s1=null;
    for(int i=0;i<s.length();i++)
    {
      char a=s.charAt(i);  
       Character chr=new Character(a);
       
      if(chr.isLetter(a))
      {
           f=1;
        s1=s.substring(0, i);   
      }
    }
    if(f==1)
    {
       // JOptionPane.showMessageDialog(null,"character not allowed");
        txtINquntity.setText(null);
    }
    
     double subVal=Double.parseDouble(txtINquntity.getText());
     double t=Double.parseDouble(lblINprice.getText());
 
   double perVal=0f;
     
    perVal=subVal*t;
   lblINtotal.setText(""+perVal);


// TODO add your handling code here:
    }//GEN-LAST:event_txtINquntityKeyReleased

    private void tblCuIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCuIdMouseClicked
DefaultTableModel mode1=(DefaultTableModel)tblCuId.getModel();
int select = tblCuId.getSelectedRow();
lblINcusId.setText(mode1.getValueAt(select,0).toString());
lblINcusname.setText(mode1.getValueAt(select,1).toString());

        // TODO add your handling code here:
    }//GEN-LAST:event_tblCuIdMouseClicked

    private void btnINremove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnINremove1ActionPerformed

int[] rows = tblCuId.getSelectedRows();
    TableModel tm= tblCuId.getModel();

    while(rows.length>0)
    {
        ((DefaultTableModel)tm).removeRow(tblCuId.convertRowIndexToModel(rows[0]));

        rows = tblCuId.getSelectedRows();
    }
    tblCuId.clearSelection();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnINremove1ActionPerformed

    private void jmproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmproActionPerformed
    new Stock().setVisible(true);   
    this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jmproActionPerformed

    private void jmcusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmcusActionPerformed
           this.setVisible(false);
           new Customer().setVisible(true); // TODO add your handling code here:
 // TODO add your handling code here:
    }//GEN-LAST:event_jmcusActionPerformed

    private void jmsupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmsupActionPerformed
        this.setVisible(false);
        new Supplier_details().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jmsupActionPerformed

    private void jmexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmexitActionPerformed
 this.setVisible(false);  
        // TODO add your handling code here:
    }//GEN-LAST:event_jmexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
          
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
         
            
            
            Invoice myFrame = new Invoice();
            myFrame.setVisible(true);
            myFrame.setExtendedState(myFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
            
           Date  d = new Date();
           String s= "hh:mm:ss a";
           SimpleDateFormat sd= new SimpleDateFormat(s);
           
            
            lblINdate.setText(LocalDate.now().toString());  
            lblNtime.setText(sd.format(d));  
          

            
                          
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnINAdd_pro;
    private javax.swing.JButton btnINclear_pro;
    private javax.swing.JButton btnINprint;
    private javax.swing.JButton btnINremove1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem jmcus;
    private javax.swing.JMenuItem jmexit;
    private javax.swing.JMenuItem jmpro;
    private javax.swing.JMenuItem jmsup;
    private javax.swing.JLabel lblINcusId;
    private javax.swing.JLabel lblINcusname;
    private static javax.swing.JLabel lblINdate;
    private javax.swing.JLabel lblINinvoiceNo;
    private javax.swing.JLabel lblINitemratio;
    private javax.swing.JLabel lblINprice;
    private javax.swing.JLabel lblINproductId;
    private javax.swing.JLabel lblINproductname;
    private javax.swing.JLabel lblINtotal;
    private static javax.swing.JLabel lblNtime;
    private javax.swing.JLabel lblSubtot;
    private javax.swing.JTable tblCuId;
    private javax.swing.JTable tbl_pro;
    private javax.swing.JTable tblproducts;
    private javax.swing.JTextField txtINquntity;
    // End of variables declaration//GEN-END:variables
}
