/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_esoft;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author PRIMESH
 */
public class Stock extends javax.swing.JFrame {

    /**
     * Creates new form Stock
     */
    public Stock() {
        initComponents();
        fillTable();
        supTable();
        proid();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSTitemratio = new javax.swing.JTextField();
        txtSTprice = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnSTupdate1 = new javax.swing.JButton();
        btnSTdelete1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSup_Prod_Detail3 = new javax.swing.JTable();
        btnClear = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblsup = new javax.swing.JTable();
        lblSTsupplierId = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSTremove = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblSTproductId = new javax.swing.JLabel();
        txtproname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmin = new javax.swing.JMenuItem();
        jmcus = new javax.swing.JMenuItem();
        jmsup = new javax.swing.JMenuItem();
        jmexit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Product Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 150, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Product Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 130, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Product Id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 130, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Price");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 130, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Item Ratio");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 130, 30));

        txtSTitemratio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSTitemratio.setForeground(new java.awt.Color(0, 0, 153));
        txtSTitemratio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSTitemratioActionPerformed(evt);
            }
        });
        getContentPane().add(txtSTitemratio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 190, 30));

        txtSTprice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSTprice.setForeground(new java.awt.Color(0, 0, 153));
        txtSTprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSTpriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtSTprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 190, 30));

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(204, 0, 0));
        btnAdd.setText("Add");
        btnAdd.setBorder(null);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 120, 40));

        btnSTupdate1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSTupdate1.setForeground(new java.awt.Color(204, 0, 0));
        btnSTupdate1.setText("Update");
        btnSTupdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSTupdate1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSTupdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 120, 40));

        btnSTdelete1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSTdelete1.setForeground(new java.awt.Color(204, 0, 0));
        btnSTdelete1.setText("Delete");
        btnSTdelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSTdelete1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSTdelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 120, 40));

        tblSup_Prod_Detail3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblSup_Prod_Detail3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblSup_Prod_Detail3.setForeground(new java.awt.Color(0, 0, 153));
        tblSup_Prod_Detail3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "null", "null", "null", "Title 4", "Title 5"
            }
        ));
        tblSup_Prod_Detail3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSup_Prod_Detail3MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSup_Prod_Detail3);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 640, 210));

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(204, 0, 0));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 120, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Supplier Id");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 120, 30));

        tblsup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblsup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblsup.setForeground(new java.awt.Color(0, 0, 153));
        tblsup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblsup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsupMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblsup);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 580, 130));

        lblSTsupplierId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSTsupplierId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSTsupplierId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblSTsupplierId, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 160, 100, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Suppliers Table");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 300, 100, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Products Table");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 100, -1));

        btnSTremove.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSTremove.setForeground(new java.awt.Color(204, 0, 0));
        btnSTremove.setText("Remove Row");
        btnSTremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSTremoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSTremove, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 490, 150, 40));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("STOCK");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 270, 40));

        lblSTproductId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSTproductId.setForeground(new java.awt.Color(0, 0, 204));
        lblSTproductId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSTproductId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblSTproductId, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 100, 30));

        txtproname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtproname.setForeground(new java.awt.Color(0, 0, 153));
        txtproname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpronameActionPerformed(evt);
            }
        });
        getContentPane().add(txtproname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 190, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_esoft/130743-blue-green-background-2149x1440-for-ipad-2.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 1640, 860));

        jMenu1.setText("File");

        jmin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jmin.setForeground(new java.awt.Color(0, 51, 51));
        jmin.setText("Invoice");
        jmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jminActionPerformed(evt);
            }
        });
        jMenu1.add(jmin);

        jmcus.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jmcus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jmcus.setForeground(new java.awt.Color(0, 51, 51));
        jmcus.setText("Add customer");
        jmcus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmcusActionPerformed(evt);
            }
        });
        jMenu1.add(jmcus);

        jmsup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jmsup.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jmsup.setForeground(new java.awt.Color(0, 51, 51));
        jmsup.setText("Add supplier");
        jmsup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmsupActionPerformed(evt);
            }
        });
        jMenu1.add(jmsup);

        jmexit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jmexit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jmexit.setForeground(new java.awt.Color(0, 51, 51));
        jmexit.setText("Exit");
        jmexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmexitActionPerformed(evt);
            }
        });
        jMenu1.add(jmexit);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSTitemratioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSTitemratioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSTitemratioActionPerformed

    private void txtSTpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSTpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSTpriceActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
String a= lblSTproductId.getText();
int id= Integer.parseInt(a);
String b=txtproname.getText();
String d=txtSTprice.getText();
double pr=Double.parseDouble(d);
String e=txtSTitemratio.getText();
int qn=Integer.parseInt(e);
String f= lblSTsupplierId.getText();



  try {
                 // TODO code application logic here
            Connection con = DBConnection.getConnection();
           
            String sqlQurey = "insert into products (productId,productName,price,itemratio,Sup_id) values (?,?,?,?,?)";
            PreparedStatement ps= con.prepareStatement(sqlQurey);
            ps.setInt(1,id);
            ps.setString(2,b);  
            ps.setDouble(3,pr);
            ps.setInt(4,qn);
            ps.setString(5,f);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Record Insert Successfully", "stock", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Record Insert Successfully ");
            fillTable();
            clear();
            proid();

            
            
        }catch (SQLException ex) {
            
            System.out.println("error");
            ex.printStackTrace();
        }


    }//GEN-LAST:event_btnAddActionPerformed

    void clear()
    {
        
        txtSTprice.setText("");
        txtSTitemratio.setText("");
        txtproname.setText("");
      
    }
     void clear1()
    {
        
        txtSTprice.setText("");
        txtSTitemratio.setText("");
        lblSTsupplierId.setText("");
        txtproname.setText("");
       proid();
    }
     void proid()
{
    
    try {
            // TODO code application logic here
            Connection con = DBConnection.getConnection();
             Statement st = con.createStatement();
        
           ResultSet rs= st.executeQuery("SELECT MAX(productId) FROM products ");
            while (rs.next()) 
            {
        int max=rs.getInt(1);
        int totmx =max+1;
        String m=Integer.toString(totmx);
         lblSTproductId.setText(m);
            }
              
            System.out.println("Record inivoiceNo get Successfully ");
                       
        }catch (SQLException ex) {
            System.out.println("error");
            ex.printStackTrace();
        }
    
}
    private void btnSTupdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSTupdate1ActionPerformed
String a= lblSTproductId.getText();
int id= Integer.parseInt(a);
String b=txtproname.getText();
String d=txtSTprice.getText();
double pr=Double.parseDouble(d);
String e=txtSTitemratio.getText();
int qn=Integer.parseInt(e);
String f= lblSTsupplierId.getText();
 try {
            // TODO code application logic here
            Connection con = DBConnection.getConnection();
           
        
            String sqlQurey = "update products Set Sup_id=? ,itemratio= itemratio +" + qn+ "  ,productName=?, price=?  where productId="+id;
            PreparedStatement ps= con.prepareStatement(sqlQurey);
           
            ps.setString(1, f);
            ps.setString(2, b);
            ps.setDouble(3, pr);
           

         
            ps.execute();
            JOptionPane.showMessageDialog(null, "Record update Successfully", "stock", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Record update Successfully ");
            fillTable();
            clear();
             proid();
            
        }catch (SQLException ex) {
            
            System.out.println("error");
            ex.printStackTrace();
        }
        // TODO add your handling code here:
        

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSTupdate1ActionPerformed

    private void btnSTdelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSTdelete1ActionPerformed
String a= lblSTproductId.getText();
int id= Integer.parseInt(a);

  try {
            // TODO code application logic here
           Connection con = DBConnection.getConnection();
          
             String sqlQurey = "delete from products where productId="+id;
            PreparedStatement ps= con.prepareStatement(sqlQurey);
             ps.execute();
             JOptionPane.showMessageDialog(null, "Record Delete Successfully", "stock", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Record Delete Successfully ");
            fillTable();
            clear();
             proid();
            
            System.out.println("Record Delete Successfully ");
        }catch (SQLException ex) {
            System.out.println("error");
            ex.printStackTrace();
            
        }
        // TODO add your handling code here:
        

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSTdelete1ActionPerformed
    
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        
        clear1();
                
    }//GEN-LAST:event_btnClearActionPerformed

    private void tblsupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsupMouseClicked
DefaultTableModel mode1=(DefaultTableModel)tblsup.getModel();
int select = tblsup.getSelectedRow();
lblSTsupplierId.setText(mode1.getValueAt(select,0).toString());


        // TODO add your handling code here:
    }//GEN-LAST:event_tblsupMouseClicked

    private void btnSTremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSTremoveActionPerformed

        DefaultTableModel mode1=(DefaultTableModel)tblsup.getModel();
        try {
            int select=tblsup.getSelectedRow();
            mode1.removeRow(select);
        } catch (Exception e) {
            System.out.println("error");

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSTremoveActionPerformed

    private void tblSup_Prod_Detail3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSup_Prod_Detail3MouseClicked
DefaultTableModel mode1=(DefaultTableModel)tblSup_Prod_Detail3.getModel();
int select = tblSup_Prod_Detail3.getSelectedRow();
lblSTproductId.setText(mode1.getValueAt(select,0).toString());
lblSTsupplierId.setText(mode1.getValueAt(select,1).toString());
txtproname.setText(mode1.getValueAt(select,2).toString());
txtSTprice.setText(mode1.getValueAt(select,3).toString());
txtSTitemratio.setText(mode1.getValueAt(select,4).toString());

        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_tblSup_Prod_Detail3MouseClicked

    private void jminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jminActionPerformed
        this.setVisible(false);
        new Invoice().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jminActionPerformed

    private void jmsupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmsupActionPerformed
       
        this.setVisible(false);
        new Supplier_details().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jmsupActionPerformed

    private void jmcusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmcusActionPerformed
          this.setVisible(false);
          new Customer().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jmcusActionPerformed

    private void jmexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmexitActionPerformed
this.setVisible(false);  
        // TODO add your handling code here:
    }//GEN-LAST:event_jmexitActionPerformed

    private void txtpronameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpronameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpronameActionPerformed

     public  void fillTable()
    {
        try {
            DefaultTableModel model = new DefaultTableModel(new String[]{}, 0);
            
            Connection con = DBConnection.getConnection();
            String sql="SELECT * FROM products";
            
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            TableModel tb = model;
            tb =  DbUtils.resultSetToTableModel(rs);
            tblSup_Prod_Detail3.setModel(tb);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
          
    }
      public  void supTable()
    {
        try {
            DefaultTableModel model = new DefaultTableModel(new String[]{}, 0);
            
            Connection con = DBConnection.getConnection();
            String sql="SELECT * FROM suppliers";
            
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            TableModel tb = model;
            tb =  DbUtils.resultSetToTableModel(rs);
            tblsup.setModel(tb);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
          
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
           //new Stock().setVisible(true);
            
            Stock myFrame = new Stock();
            myFrame.setVisible(true);
            myFrame.setExtendedState(myFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
            myFrame.setExtendedState(JFrame.MAXIMIZED_BOTH);
           
           
            
            
            });
    }
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSTdelete1;
    private javax.swing.JButton btnSTremove;
    private javax.swing.JButton btnSTupdate1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem jmcus;
    private javax.swing.JMenuItem jmexit;
    private javax.swing.JMenuItem jmin;
    private javax.swing.JMenuItem jmsup;
    private javax.swing.JLabel lblSTproductId;
    private javax.swing.JLabel lblSTsupplierId;
    private static javax.swing.JTable tblSup_Prod_Detail3;
    private javax.swing.JTable tblsup;
    private javax.swing.JTextField txtSTitemratio;
    private javax.swing.JTextField txtSTprice;
    private javax.swing.JTextField txtproname;
    // End of variables declaration//GEN-END:variables
}
